# -*- coding: utf-8 -*-
"""Fraud Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aJg-FnirnlQpJyc9hjO84jlxdl9YOTSv
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/drive/MyDrive/Datasets/fraudTrain.csv')

df.head()

df.tail()

df.info()

df.isnull().sum()

df['is_fraud'].value_counts()

"""**EDA and Data Cleaning**"""

df.drop(columns = ['Unnamed: 0','trans_num','trans_date_trans_time','cc_num','first','last','street','city','state','dob','zip'], inplace = True)
df

"""# **Preprocess**"""

df.duplicated().sum()

"""# Feature Scaling"""

categorical_cols = ['merchant','gender','category','job']
numerical_cols = ['amt','lat','long','city_pop','unix_time','merch_lat','merch_long']

categorical_cols

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler ,OrdinalEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers = [('num', StandardScaler(), numerical_cols),
                    ('cat', OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), categorical_cols)
    ]
)

"""# Split"""

X = df.drop(columns = ['is_fraud'], inplace=False)
y = df['is_fraud']

"""Model Traning"""

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression())    # random forest , svm, xgboost, linear regression   models i have to use
])

model.fit(X, y)

model.score(X, y)

"""Test dataset"""

df_test = pd.read_csv('/content/drive/MyDrive/Datasets/fraudTest.csv')

df_test.info()

df_test.drop(columns = ['Unnamed: 0','trans_num','trans_date_trans_time','cc_num','first','last','street','city','state','dob','zip'], inplace = True)
df_test

df_test.duplicated().sum()

X_test = df_test.drop(columns = ['is_fraud'], inplace=False)
y_test = df_test['is_fraud']

pred = model.predict(X_test)
pred

"""to be deleted very soon sadly 1"""

drop_x = X.drop(columns=['merchant','category','gender','job'], inplace=False)
drop_x

"""to be deleted very soon sadly 2"""

from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(drop_x, y)

from sklearn.metrics import precision_score, recall_score, f1_score

print("Logistic Regression: Simple baseline. ")
print("Accuracy: ",accuracy_score(y_test, pred))
print("Precision: ",precision_score(y_test, pred))
print("Recall: ",recall_score(y_test, pred))
print("F1 Score: ",f1_score(y_test, pred))
print("Confusion Matrix: \n",confusion_matrix(y_test, pred))
print("Classification Report: \n",classification_report(y_test, pred))

"""# `XGBOOST`"""

from xgboost import XGBClassifier

xgb_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(random_state=1))
])

xgb_model.fit(X, y)

pred_xgb = xgb_model.predict(X_test)

print("XGBoost (Very Powerful): Often gives best performance in fraud detection")
print("Accuracy: ",accuracy_score(y_test, pred_xgb))
print("Precision: ",precision_score(y_test, pred_xgb))
print("Recall: ",recall_score(y_test, pred_xgb))
print("F1 Score: ",f1_score(y_test, pred_xgb))

"""## **RANDOM** **FOREST**"""

from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=1))
])

rf_model.fit(X, y)

pred_rf = rf_model.predict(X_test)

print("Random Forest: Handles imbalance better.")
print("Accuracy: ",accuracy_score(y_test, pred_rf))
print("Precision: ",precision_score(y_test, pred_rf))
print("Recall: ",recall_score(y_test, pred_rf))
print("F1 Score: ",f1_score(y_test, pred_rf))

"""**Unsupervised Learning: Isolation Forest**


"""

from sklearn.pipeline import Pipeline
from sklearn.ensemble import IsolationForest

iso_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', IsolationForest(n_estimators=200,
        contamination=0.0017,   # ~0.17% fraud ratio
        random_state=42
                                   ))
])

iso_model.fit(X)

iso_preds = iso_model.predict(X_test)

# Convert output:
# -1 → anomaly (fraud)
#  1 → normal

iso_preds = np.where(iso_preds == -1, 1, 0)


print("Accuracy: ",accuracy_score(y_test, iso_preds))
print("Precision: ",precision_score(y_test, iso_preds))
print("Recall: ",recall_score(y_test, iso_preds))
print("F1 Score: ",f1_score(y_test, iso_preds))

import pandas as pd
import matplotlib.pyplot as plt

# Model scores
data = {
    "Model": ["Logistic Regression", "Random Forest", "XGBoost","Isolation Forest"],
    "Accuracy": [0.9953915558042824, 0.9974051634009274, 0.9963902619849241, 0.9926113737338476],
    "Precision": [0.8709677419354839, 0.7399317406143344, 0.5381239714755897, 0.31085604973696796],
    "Recall": [0.84375, 0.5053613053613054, 45734265734265733, 0.30303030303030304],
    "F1 Score": [0.8571428571428571, 0.6005540166204986, 0.4944556451612903, 0.30689329556185082]
}

# Create dataframe
df_scores = pd.DataFrame(data)

# Print table
print("Model Performance Comparison")
print(df_scores)

# Plot
df_scores.set_index("Model").plot(kind="bar", figsize=(10,6))

plt.title("Machine Learning Model Performance Comparison")
plt.ylabel("Score")
plt.ylim(0.20, 1.00)
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(loc="upper right")

plt.show()